DROP TABLE IF EXISTS `iom_ci_source_rel`;
CREATE TABLE `iom_ci_source_rel`  (
  `ID` decimal(22, 0) NOT NULL COMMENT 'ID',
  `SOURCE_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '数据来源ID',
  `CI_TYPE_ID` decimal(22, 0) NOT NULL COMMENT '大类ID',
  `CI_CODE` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'CICODE',
  `DOMAIN_ID` varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '数据域ID',
  `CJR_ID` decimal(22, 0) NOT NULL COMMENT '创建人',
  `CJSJ` timestamp(0) NOT NULL COMMENT '创建时间',
  `XGR_ID` decimal(22, 0) NULL DEFAULT NULL COMMENT '修改人',
  `XGSJ` timestamp(0) NULL DEFAULT NULL COMMENT '修改时间',
  `YXBZ` int(0) NOT NULL COMMENT '有效标志',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '数据源和对象关联关系表' ROW_FORMAT = Dynamic;

ALTER TABLE `iomci`.`iom_ci_data_rel` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `TARGET_TYPE_ID`;
ALTER TABLE `iomci`.`iom_ci_dir` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `DIR_DESC`;
ALTER TABLE `iomci`.`iom_ci_info` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `ATTRS_STR`;
ALTER TABLE `iomci`.`iom_ci_kpi` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `MAXIMUM`;
ALTER TABLE `iomci`.`iom_ci_kpi_class` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `NAME`;
ALTER TABLE `iomci`.`iom_ci_label` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域' AFTER `LABEL_RULE_INFO`;
ALTER TABLE `iomci`.`iom_ci_rel` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `LINE_ANIME`;
ALTER TABLE `iomci`.`iom_ci_rlt_line` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '所属域' AFTER `OP_TYPE`;
ALTER TABLE `iomci`.`iom_ci_rlt_node` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '所属域' AFTER `Y`;
ALTER TABLE `iomci`.`iom_ci_rlt_node_cdt` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '所属域' AFTER `STOR`;
ALTER TABLE `iomci`.`iom_ci_rlt_rule` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '所属域' AFTER `VALID_DESC`,
COMMENT = '数据提取规则表\r\n配置报表数据表';
ALTER TABLE `iomci`.`iom_ci_type` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `SORT`;
ALTER TABLE `iomci`.`iom_ci_type_data` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `DATA_35`;
ALTER TABLE `iomci`.`iom_ci_type_focus_rel` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `CJR_ID`;
ALTER TABLE `iomci`.`iom_ci_type_rel` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `CJR_ID`;
ALTER TABLE `iomci`.`iom_ci_type_rel_diagram` MODIFY COLUMN `DOMAIN_ID` varchar(25) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `DIAG_TYPE`;
ALTER TABLE `iomci`.`iom_ci_version` MODIFY COLUMN `DOMAIN_ID` varchar(0) NULL DEFAULT NULL COMMENT '数据域ID' AFTER `YXBZ`;